const LEGACY_TEXTURE_KEY = "lazuli-tx-v1";
const STRICT_V7_TEXTURE_KEY =
  `${LEGACY_TEXTURE_KEY}~LZGX7:${LEGACY_TEXTURE_KEY.length}`;
const TEXTURE_WIDTH = 4;
const TEXTURE_HEIGHT = 4;
const TEXTURE_FORMAT = 6;
const TEXTURE_MODE0 = 0x00000020;
const TEXTURE_MODE1 = 0x00002000;
const TEXTURE_LEVEL_COUNT = 3;
const TEXTURE_PAYLOAD_BYTES = 84;
const XFB_DESTINATION = 0x00120000;
const XFB_WIDTH = 4;
const XFB_HEIGHT = 4;
const XFB_STRIDE = XFB_WIDTH * 4;

// These packets are intentionally committed data, not a second packet
// encoder. The adjacent Node test extracts the live browser_boot.rs producer
// dependency chain and requires byte-for-byte identity with both fixtures.
const FIRST_PACKET_BASE64 = [
  "TFpHWAcAoABQBgAAAAAAAAIAAAABAAAAAQAAAKAAAABQAQAAkAEAAGADAACgBQAAwAUAALAAAABAAAAA0AEAAEACAAAVAAAAYAAAAAAAAAAAAAAABAAAAAQA",
  "AAAEAAAABAAAAAAAEgAQAAAAAQAAAAAAAAAAAAAAsABAAAQAAAAAAAAAAAAAAAAAAAADQAAAAAAAAAABAAAAAIIAAAAAAAAAAQAEAAAAAAAAAAAAAAAAAAAA",
  "CAAAAAAAPwAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAgAAAA/////wAAAAD/////AAAAAP////8AAAAA/////wAAAAD/////AAAAAP////8AAAAA/////wAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABUAAAAAAAAAVAAAAABQEgATAAAA",
  "BAAAAAQAAAABAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPj/SADA/0gAwAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAgAAAAMAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAPQoXPwAAAAAAAAAAAACAPwAAgD8AAIA/AACAPwAAgD8AAIA/",
  "AACAPwAAgD8AAIA/zczMPc3MzD0AAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAA",
  "AAAAAIA/AAAAAAAAAAAAAIA/AACAQAAAAAAAAAAAAACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/ZmbmP83MzD0AAIA/AAAAAAAAAAAAAIA/",
  "AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AACAQAAAgEAAAAAAAACAPwAA",
  "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/ZmbmP2Zm5j8AAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/",
  "AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/PQoXPwAAgEAAAAAAAACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/zczMPWZm",
  "5j8AAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/",
  "bGF6dWxpLXR4LXYxfkxaR1g3OjEyAAAAAAAAAAAAAAADFCU2R1hpeoucrb7P4PECEyQ1RldoeYqbrL3O3/ABEiM0RVZneImaq7zN3u8AESIzRFVmd4iZqrvM",
  "3e7/ECEyQ1RldoeYqbrL3O3+DyAxQlNkdYYAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
].join("");
const RESIDENT_PACKET_BASE64 = [
  "TFpHWAcAoADwBQAAAAAAAAIAAAABAAAAAQAAAKAAAABQAQAAkAEAAGADAACgBQAAwAUAALAAAABAAAAA0AEAAEACAAAVAAAAAAAAAAAAAAAAAAAABAAAAAQA",
  "AAAEAAAABAAAAAAAEgAQAAAAAgAAAAAAAAAAAAAAsABAAAQAAAAAAAAAAAAAAAAAAAADQAAAAAAAAAABAAAAAIIAAAAAAAAAAQAEAAAAAAAAAAAAAAAAAAAA",
  "CAAAAAAAPwAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAgAAAA/////wAAAAD/////AAAAAP////8AAAAA/////wAAAAD/////AAAAAP////8AAAAA/////wAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABUAAAAAAAAAAAAAAABQEgATAAAA",
  "BAAAAAQAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPj/SADA/0gAwAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAgAAAAMAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAPQoXPwAAAAAAAAAAAACAPwAAgD8AAIA/AACAPwAAgD8AAIA/",
  "AACAPwAAgD8AAIA/zczMPc3MzD0AAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAA",
  "AAAAAIA/AAAAAAAAAAAAAIA/AACAQAAAAAAAAAAAAACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/ZmbmP83MzD0AAIA/AAAAAAAAAAAAAIA/",
  "AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AACAQAAAgEAAAAAAAACAPwAA",
  "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/ZmbmP2Zm5j8AAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/",
  "AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/PQoXPwAAgEAAAAAAAACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/zczMPWZm",
  "5j8AAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/",
  "bGF6dWxpLXR4LXYxfkxaR1g3OjEyAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
].join("");

function generationU32(value) {
  if (
    !Number.isSafeInteger(value) ||
    value < 0 ||
    value > 0xffffffff
  ) {
    throw new RangeError("GX mip activation generation must be a u32");
  }
  return value;
}

function activationMipPixels() {
  return Uint8Array.from(
    { length: TEXTURE_PAYLOAD_BYTES },
    (_unused, index) => (3 + index * 17) & 0xff,
  );
}

function assertCanonicalPreflight(preflight) {
  if (
    preflight === null ||
    typeof preflight !== "object" ||
    preflight.accepted !== true ||
    preflight.classification !== "genuine-mip" ||
    preflight.mode0 !== TEXTURE_MODE0 ||
    preflight.mode1 !== TEXTURE_MODE1 ||
    preflight.format !== TEXTURE_FORMAT ||
    preflight.width !== TEXTURE_WIDTH ||
    preflight.height !== TEXTURE_HEIGHT ||
    preflight.levelCount !== TEXTURE_LEVEL_COUNT
  ) {
    throw new Error(
      "GX mip activation frame requires the live canonical strict-V7 preflight",
    );
  }
}

export function buildGxMipActivationOracleTexture({
  strictV7Preflight,
} = {}) {
  assertCanonicalPreflight(strictV7Preflight);
  const mipPixels = activationMipPixels();
  return {
    key: LEGACY_TEXTURE_KEY,
    address: 0x00125000,
    textureCopyIndex: 19,
    width: TEXTURE_WIDTH,
    height: TEXTURE_HEIGHT,
    format: TEXTURE_FORMAT,
    mode0: TEXTURE_MODE0,
    mode1: TEXTURE_MODE1,
    levelCount: TEXTURE_LEVEL_COUNT,
    wrapS: 0,
    wrapT: 0,
    magFilter: 0,
    minFilter: 1,
    maxAnisotropy: 0,
    pixels: mipPixels.subarray(0, TEXTURE_WIDTH * TEXTURE_HEIGHT * 4),
    mipPixels,
    strictV7Preflight,
  };
}

export function buildGxMipActivationOracleFrame({
  generation = 1,
  draw,
} = {}) {
  generation = generationU32(generation);
  if (
    draw === null
    || typeof draw !== "object"
    || draw.topology !== 0
    || draw.vertexCount !== 4
    || !(draw.vertices instanceof Float32Array)
    || draw.vertices.length !== 4 * 36
    || !(draw.tevState instanceof Uint8Array)
    || !Array.isArray(draw.textures)
    || !(draw.postCullEvidence instanceof Uint8Array)
    || draw.postCullEvidence.length !== 1
    || draw.postCullEvidence[0] !== 0x0f
  ) {
    throw new Error(
      "GX mip activation frame requires producer-generated managed evidence",
    );
  }
  assertCanonicalPreflight(draw.textures[0]?.strictV7Preflight);
  return {
    copyToXfb: true,
    index: generation,
    sourceX: 0,
    sourceY: 0,
    width: XFB_WIDTH,
    sourceHeight: XFB_HEIGHT,
    height: XFB_HEIGHT,
    destination: XFB_DESTINATION,
    stride: XFB_STRIDE,
    clear: false,
    copyState: {
      zMode: 0,
      blendMode: 0,
      pixelControl: 0,
      copyCommand: 0x004003,
      clearRgba: [0, 0, 0, 0],
      clearDepth: 0,
      copyScale: 256,
      copyFilter: [(32 << 12) | (32 << 18), 0],
    },
    geometry: {
      drawCalls: 1,
      vertices: 4,
      draws: [draw],
    },
  };
}

function packetFromBase64(base64, name) {
  if (base64.length === 0) {
    throw new Error(`GX mip activation ${name} packet fixture is empty`);
  }
  const binary = globalThis.atob(base64);
  return Uint8Array.from(
    { length: binary.length },
    (_unused, index) => binary.charCodeAt(index),
  );
}

export function buildGxMipActivationOraclePacket({
  resident = false,
} = {}) {
  if (typeof resident !== "boolean") {
    throw new TypeError("GX mip activation resident state must be boolean");
  }
  return packetFromBase64(
    resident ? RESIDENT_PACKET_BASE64 : FIRST_PACKET_BASE64,
    resident ? "resident" : "first",
  );
}

export const gxMipActivationOracle = Object.freeze({
  packetVersion: 7,
  legacyKey: LEGACY_TEXTURE_KEY,
  key: STRICT_V7_TEXTURE_KEY,
  keySuffix: `~LZGX7:${LEGACY_TEXTURE_KEY.length}`,
  width: TEXTURE_WIDTH,
  height: TEXTURE_HEIGHT,
  format: TEXTURE_FORMAT,
  mode0: TEXTURE_MODE0,
  mode1: TEXTURE_MODE1,
  mipLevelCount: TEXTURE_LEVEL_COUNT,
  payloadBytes: TEXTURE_PAYLOAD_BYTES,
  expectedFirstUpload: Object.freeze({
    resourceIdentities: 1,
    textureWrites: TEXTURE_LEVEL_COUNT,
    textureUploadBytes: TEXTURE_PAYLOAD_BYTES,
    packetPayloadBytes: TEXTURE_PAYLOAD_BYTES,
  }),
  expectedResidentUpload: Object.freeze({
    resourceIdentities: 1,
    textureWrites: 0,
    textureUploadBytes: 0,
    packetPayloadBytes: 0,
  }),
});
