#!/usr/bin/env node
// SPDX-License-Identifier: GPL-3.0-only

import assert from "node:assert/strict";
import { readFile, readdir } from "node:fs/promises";
import test from "node:test";

import { assertGenericFrontend } from "./build_web.mjs";
import {
  releaseAssets,
  rollbackReleaseAssets,
  sha256Hex,
  validateRelease,
  verifyAssetBytes,
} from "../web/release.mjs";

test("generated public artifact contains only the release surface", async () => {
  const directory = new URL("../web/dist/", import.meta.url);
  const release = JSON.parse(await readFile(new URL("release.json", directory), "utf8"));
  await validateRelease(release);
  const [
    frontend,
    rendererJavascript,
    residentWorker,
    sourcePage,
    thirdPartyNotices,
    vendoredFontLicense,
  ] = await Promise.all([
    readFile(new URL(`.${release.frontend.url}`, directory), "utf8"),
    readFile(
      new URL(`.${release.renderer.javascript.url}`, directory),
      "utf8",
    ),
    readFile(new URL(`.${release.runtime.worker.url}`, directory), "utf8"),
    readFile(new URL("source/index.html", directory), "utf8"),
    readFile(new URL("THIRD-PARTY-NOTICES.txt", directory)),
    readFile(
      new URL("../licenses/Dolphin-fonts-Apache-2.0.txt", import.meta.url),
    ),
  ]);

  assert.doesNotThrow(() => assertGenericFrontend(frontend));
  assert.match(frontend, /data-surface="release"/);
  assert.match(
    frontend,
    /SPDX-License-Identifier: GPL-3\.0-only AND Apache-2\.0/,
  );
  assert.match(
    frontend,
    /href="\/source\/"[^>]*>Legal<\/a>/,
  );
  assert.doesNotMatch(frontend, />GPL-3\.0-only<|>Apache-2\.0 font notice</);
  assert.doesNotMatch(frontend, /data-surface="debug"|LAZULI DEBUG UI/);
  for (const id of ["disc-file", "display", "controller-controls"]) {
    assert.match(frontend, new RegExp(`id="${id}"`));
  }
  assert.match(
    frontend,
    /\.shell\[data-surface="release"\]\s*\{[^}]*position:\s*fixed;[^}]*inset:\s*0;/s,
  );
  assert.match(
    frontend,
    /\.shell\[data-surface="release"\] #controller-controls\s*\{[^}]*display:\s*grid;/s,
  );
  assert.match(
    frontend,
    /body\[data-status="waiting"\] \.shell\[data-surface="release"\] header/,
  );
  assert.doesNotMatch(
    frontend,
    /id="(?:runner-controls|pause-runner|resume-runner|diagnostics|disc-url|load-disc-url|extend-cycles|extend-dispatches|extend-runner|runner-rest-ms|apply-throttle|runner-render-every|apply-presentation|snapshot-runner|stop-runner)"/,
  );
  assert.equal(frontend.match(/id="result"/g)?.length, 1);
  assert.match(
    frontend,
    /<pre id="result" data-testid="browser-boot-result" hidden aria-hidden="true"><\/pre>\s*<\/main>/,
  );
  assert.doesNotMatch(
    frontend,
    /lazuliCompatibilityDebug|selectCompatibilityScenario|runnerSearchForSurface|selectedCompatibilityRunnerSearch/,
  );
  assert.doesNotMatch(
    frontend,
    /__LAZULI_RESIDENT_RELEASE_RUNTIME__|\/ppcwasmjit\.wasm|\/browser_dsp\.wasm/,
  );
  assert.ok(frontend.includes(release.renderer.javascript.url));
  assert.ok(!frontend.includes("/browser_renderer.js"));
  assert.ok(frontend.includes(release.runtime.worker.url));
  assert.ok(frontend.includes(release.runtime.core.url));
  assert.ok(frontend.includes(release.runtime.dispatcher.url));
  assert.ok(frontend.includes(release.runtime.coordinator.url));
  assert.ok(!frontend.includes("/browser_dsp.wasm"));
  assert.ok(residentWorker.includes(`from "${release.runtime.adapter.url}"`));
  assert.ok(!residentWorker.includes('from "./resident-machine.mjs"'));
  assert.ok(rendererJavascript.includes(release.renderer.wasm.url));
  assert.ok(!rendererJavascript.includes("browser_renderer_bg.wasm"));
  assert.deepEqual(thirdPartyNotices, vendoredFontLicense);
  assert.match(
    sourcePage,
    /Lazuli's code is GPL-3\.0-only\. This release also includes Apache-2\.0 alternative IPL font data and Dolphin's free replacement DSP ROM images\./,
  );
  assert.match(
    sourcePage,
    /generated by Dolphin's <code>gc-font-tool<\/code> from Droid Sans, copyright 2006–2014 Google Corporation, and are distributed under the Apache License 2\.0\./,
  );
  assert.match(
    sourcePage,
    /href="\/THIRD-PARTY-NOTICES\.txt">Apache-2\.0 and attribution<\/a>/,
  );
  assert.match(sourcePage, /DSP ROM attribution[\s\S]*upstream source and contributor history/);
  assert.equal(release.source.license.expression, "GPL-3.0-only");
  for (const asset of [...releaseAssets(release), ...rollbackReleaseAssets(release)]) {
    await verifyAssetBytes(asset, await readFile(new URL(`.${asset.url}`, directory)));
  }
  assert.doesNotMatch(
    JSON.stringify(release),
    /font_(?:japanese|western)\.bin/,
  );
  const rootFiles = await readdir(directory);
  assert.ok(rootFiles.includes("THIRD-PARTY-NOTICES.txt"));
  assert.ok(rootFiles.includes("source"));
  assert.ok(!rootFiles.includes("source.html"));
  assert.ok(!rootFiles.includes("app.html"));
  assert.ok(!rootFiles.includes("font_japanese.bin"));
  assert.ok(!rootFiles.includes("font_western.bin"));
  assert.ok(!rootFiles.includes("browser_renderer.js"));
  assert.ok(!rootFiles.includes("browser_renderer_bg.wasm"));
  assert.ok(!rootFiles.includes("browser_dsp.wasm"));
});
